name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest] # ubuntu-latest, mac-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node LTS
        uses: actions/setup-node@v3

        with:
          node-version: lts/*
      - run: npm ci
      - run: npm test